[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/capabilities.html"
  to = "/capabilities"
  status = 301

[[redirects]]
  from = "/reverse-engineering.html"
  to = "/reverse-engineering"
  status = 301

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/quote.html"
  to = "/quote"
  status = 301

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
